name: 'Turbo Changed Packages'
description: 'A Github Action to return the changed packages from a Turborepo project'
author: 'Packfleet'
branding:
  icon: git-branch
  color: green
inputs:
  prefix:
    required: false
    description: 'Prefix to filter the packages by'
  extract-prefix:
    required: false
    type: boolean
  from:
    required: false
    description: 'Start of the commit range to check (can be a commit hash or a branch name).'
  to:
    required: false
    description: 'End of the commit range to check (can be a commit hash or branch). If not provided, will be the current commit of the head branch on a `pull_request` event. For a push event, it will be the current commit of the current branch.'
  working-directory:
    required: false
    description: 'Path to the root of the turborepo project.'
    default: './'
outputs:
  changed:
    description: 'True if the workspace changed, otherwise false.'

runs:
  using: 'node16'
  main: 'dist/index.js'
